### ISSUE TITLE
Obstructed Cloudflare Captcha

### ISSUE THREAD

**Issue by AlifianK** [TuxedoTako/4chan-xt#19]
Is it possible to resize the reply box? Linking the issue here https://github.com/drunohazarb/4chan-captcha-solver/issues/12 for visibility.

**Comment by TuxedoTako** [comment]
I don't know if it's a regional thing, but I can't reproduce the issue. I'll try to fix it when I get it, but as long as that doesn't happen, I don't know how to fix it. PR welcome I guess.

**Comment by saxamaphone69** [comment]
I finally got it to appear using Firefox.

The HTML renders as so:
```html
<div class="captcha-root"><div class="captcha-container" style="position: relative; width: 300px;"><button id="t-load" type="button" data-board="g" data-tid="0" style="font-size: 11px; padding: 0px; width: 90px; box-sizing: border-box; margin: 0px 6px 0px 0px; vertical-align: middle; height: 18px;" disabled="">Loading</button><input id="t-resp" name="t-response" placeholder="Type the CAPTCHA here" autocomplete="off" type="text" style="width: 160px; box-sizing: border-box; text-transform: uppercase; font-size: 11px; height: 18px; margin: 0px; padding: 0px 2px; font-family: monospace; vertical-align: middle;"><button id="t-help" type="button" data-tip="Help" tabindex="-1" style="font-size: 11px; padding: 0px; width: 20px; box-sizing: border-box; margin: 0px 0px 0px 6px; vertical-align: middle; height: 18px;">?</button><iframe id="t-frame" style="border: 0px; width: 100%; height: 80px; margin-top: 2px; position: relative; display: block;" src="https://sys.4chan.org/captcha?framed=1&amp;board=g"></iframe><div id="t-cnt" style="height: 80px; margin-top: 2px; position: relative; display: none;"><div id="t-bg" style="width: 100%; height: 100%; position: absolute; background-repeat: no-repeat; background-position: left top;"></div><div id="t-fg" style="width: 100%; height: 100%; position: absolute; background-repeat: no-repeat; background-position: left top;"></div></div><input id="t-slider" autocomplete="off" type="range" min="0" max="100" style="width: 100%; box-sizing: border-box; visibility: hidden; margin: 0px; transition: box-shadow 10s ease-out 0s; box-shadow: rgb(29, 141, 196) 0px 0px 4px 2px; position: relative;"><div id="t-msg" style="width: 100%; position: absolute; top: 50%; text-align: center; font-size: 14px; filter: inherit; display: none;"></div><input name="t-challenge" type="hidden"></div></div>
```

The key element there being `#t-frame`, which is an `iframe`. If you never get the 'Verification needed' page, then `https://sys.4chan.org/captcha?framed=1&board=g` leads to a blank page. When you do need it, this is the page in full:
https://pastebin.com/8XcgiEKg

What's interesting is that there is actually a CSS rule there `@media (max-width:301px){#cf-please-wait,#chk-hdr{display:none!important}`, which is the big 'Checking if the site...' text that is pushing everyone's verification down.

However, when I get the verification within the QR, the 'Checking if the site' text never appears for me. Even when forcing the QR to be less, or greater, than 300px.

edit: `.captcha-container` has `width: 300px;` which is making things not play nice all the time.

`#t-frame` is given `height: 80px`. Removing it seems to do the trick. Not beautifully, but it does the trick. There could also be an `overflow` used somewhere, but since I'm not getting the exact same issue, it's hard to test.

![image](https://github.com/TuxedoTako/4chan-xt/assets/877480/a10ff1fa-86e4-4bd2-ad60-018b16c407d2)

**Comment by TuxedoTako** [comment]
The `t-frame` element is created in [s.4cdn.org/js/core.min.1110.js](https://s.4cdn.org/js/core.min.1110.js), including its hard coded height. It's sets its style in the `style` attribute directly, so I can't overwrite it with css. It also sets `overflow: hidden` this way.

I think this is an upstream issue, seeing that the height comes from 4chan itself. But I can't test if I get it with 4chan's native extension, since I don't get that text above the cloudflare checkbox.

**Comment by AlifianK** [comment]
@TuxedoTako You can close this issue if you consider it unfixable. If there is any consolation, the issue only appears when changing IP, and it's fine after that. I personally only have this problem once, and that was more than a week ago. I guess we have to wait until the election season is over.

**Comment by AlifianK** [comment]
Okay I tried this again, it seems like it was fixed upstream.
![Screenshot_2024-01-10-00-25-44-554_com kiwibrowser browser](https://github.com/TuxedoTako/4chan-xt/assets/50392169/373e237f-1abd-46ec-ba71-34521e4537f2)
