### ISSUE TITLE
Safari on maxOS does not render all header bar emojis

### ISSUE THREAD

**Issue by Alen3000** [TuxedoTako/4chan-xt#38]
At a quick glance this includes:

- Prefetch (U+1F5F2)
- Refresh (U+1F5D8)
- Menu in thread watcher (U+1F783)

Additionally, the emojis seem have to varying sizes.

<img width="895" alt="image" src="https://github.com/TuxedoTako/4chan-xt/assets/85650894/5ec00991-0626-4566-a6aa-49fe377a8411">

Appreciate that Font Awesome is bloat, but it may not be an unreasonable use case to inline some simple, sensibly licensed SVG icons or similar, or finding some other, better way of normalising sizes.

**Comment by saxamaphone69** [comment]
Perhaps emoji/unicode icons need a [specific font stack](https://www.client9.com/css-color-emoji-stack/) to ensure consistent rendering. `'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol', 'Noto Color Emoji'` somewhere? Though when an emoji version doesn't exist, I dunno.

**Comment by TuxedoTako** [comment]
On windows, the emoji are from Segoe UI Symbol, Segoe UI Emoji is for multi colored pictures instead of the symbols in the fonts color. 

I don't have an apple device to test on, so I can't check what font stack would have that effect on mac.

**Comment by Alen3000** [comment]
At a glance it seems like it's just inheriting the `font-family` from whatever theme is picked, by default the yotsuba themes use `font-family: arial, helvetica, sans-serif`.

Setting `font-family: 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol', 'Noto Color Emoji'` seems to only really make the reply icon appear more consistent by using a coloured emoji:

![](https://github.com/TuxedoTako/4chan-xt/assets/85650894/649f7d2e-56a0-48d2-b84a-426dc07a8191)

When trying to use the characters elsewhere in the system they don't seem to render nicely either. Perhaps it may be worth considering alternative characters, if you don't fancy embedding icons?

Could consider setting the font family as per https://github.com/TuxedoTako/4chan-xt/issues/38#issuecomment-1998967698 and replacing:
- "🗘" with "🔄" 
- "🗲︎" with "⚡️"

I'm not sure if there's a nice way of rendering these replacements in a monochromatic fashion on Windows/Linux, however.

**Comment by TuxedoTako** [comment]
>Could consider setting the font family as per https://github.com/TuxedoTako/4chan-xt/issues/38#issuecomment-1998967698 and replacing:

Just to be clear, I'm on windows, and the header icons look like this on windows: 

![msedge_eWny6KwA5G](https://github.com/TuxedoTako/4chan-xt/assets/126348645/c33476d7-0edd-4f1d-96d6-637acdf242cc)

The monochrome icons are from Segoe UI Symbol, which is why that has to be before Segoe UI Emoji. I'm hoping to find an Segoe UI Symbol equivalent on mac, but because I don't own one, I can't test mac font stacks myself myself. 

>Could consider setting the font family as per https://github.com/TuxedoTako/4chan-xt/issues/38#issuecomment-1998967698 and replacing:

On windows, those look like this:

Without Segoe UI Symbol:

![image](https://github.com/TuxedoTako/4chan-xt/assets/126348645/b6f57d18-4eeb-4775-8042-b90173ec3ff0)

With Segoe UI Symbol:

![msedge_bQUQ2mOEkr](https://github.com/TuxedoTako/4chan-xt/assets/126348645/53106ebe-1d99-4a27-b6cc-87597ff78be0)

So those are usable, but that doesn't change the fact that a lot of icons are colored emoji on mac. It might also be broken on Linux.

If we can't find a good font for mac, I'm considering using the icons from https://github.com/ccd0/4chan-x/pull/2395. I would prefer if apple has a good icon font I can put in the stack, but picking and choosing icons is better than including all of of font awesome at least.

**Comment by TuxedoTako** [comment]
Since no apple user provided a good icon font, I'm switching back to font awesome. But this time only importing the icons that are actually used.

This will be in the next release, soonish. Code is already in the repo.

**Comment by TuxedoTako** [comment]
Moved back to Font Awesome in [2.7.0](https://github.com/TuxedoTako/4chan-xt/releases).

**Comment by saxamaphone69** [comment]
<img width="617" alt="Screenshot 2024-05-22 at 6 41 27 pm" src="https://github.com/TuxedoTako/4chan-xt/assets/877480/ad99b90c-876f-4245-8207-fc9de8f05473">

FWIW, the menu icon at the end of posts and the thread watcher doesn't render on macOS/iOS either.
