### ISSUE TITLE
Can you add a button to revert to original filename when you don't want it to be auto randomized?

### ISSUE THREAD

**Issue by yuk1w1fe** [TuxedoTako/4chan-xt#40]

**Comment by TuxedoTako** [comment]
You can turn off "Randomize Filename" in the settings.

**Comment by yuk1w1fe** [comment]
I mean, I always use that feature, but sometimes I want to keep the original filename

**Comment by vampiricwulf** [comment]
A suggestion for implementation is to change it into something like "Remember Spoiler" where there appears an R checkbox in the fileinput area to toggle filename ranzomizer and people could select "Remember Randomizer" to keep it checked/unchecked between posts.

I personally never use the feature as is since I prefer original filenames. However, if it's pasted from clipboard it might be something I actually check.

**Comment by saxamaphone69** [comment]
Check https://github.com/ccd0/4chan-x/pull/2927 for further discussion, plus a PR.

**Comment by vampiricwulf** [comment]
I'd second ccd0's wish for a non-destructive version, probably catch the original filename before https://github.com/ccd0/4chan-x/blob/master/src/Posting/QR.post.coffee#L209 (https://github.com/TuxedoTako/4chan-xt/blob/project-XT/src/Posting/QR.js#L1913) and store it so that toggling it off restores the filename.

**Comment by TuxedoTako** [comment]
Released in [2.7.0](https://github.com/TuxedoTako/4chan-xt/releases).

**Comment by yuk1w1fe** [comment]
very based. Thank you
