### ISSUE TITLE
Restoring deleted posts doesn't work well with Threading.

### ISSUE THREAD

**Issue by Ilya1933** [TuxedoTako/4chan-xt#55]
Hovering over a reply to a deleted post while having threading on is weird. It's hard to explain, but it changes the layout of the page by making threads as the deleted posts get added. It's very annoying.

**Comment by TuxedoTako** [comment]
The insert on hover is because I noticed that the restore button from the menu skips posts that are already restored when hovering and this already exists, so to solve that I insert the deleted posts when hovering. Which for theading recalculates the thread, since the deleted post might be the parent of an existing post. As a threading user, where do you want the posts to appear?

**Comment by Ilya1933** [comment]
I don't really care about where the posts appear, so long as it doesn't move the page around while I'm trying to use it. This is a new issue with 4chanXT; in 4chanX, the deleted post only appeared as a pop up and didn't move anything around. If you want the deleted posts to directly appear on the page, then I think that the best solution would be to do it just as when new posts appear: directly at the bottom of the thread until you refresh the page, where they're then integrated into threads.

**Comment by TuxedoTako** [comment]
Should be fixed in [2.8.2](https://github.com/TuxedoTako/4chan-xt/releases).

**Comment by Ilya1933** [comment]
Thank you for fixing it.
